remote_theme: just-the-docs/just-the-docs

permalink: pretty

logo: "/GalaxyCore.png"
aux_links:
        "Follow on Github":
         - "//github.com/GalaxyCore-net/"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 GalaxyCore.net. <a href='https://galaxycore.net/impressum'>Impressum</a> <a href='https://galaxycore.net/datenschutzerklaerung'>Datenschutz</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

