name: "Deploy to Pages"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: jerryjvl/jekyll-build-action@v1    # Choose any one of the Jekyll Actions
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.9
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.2
